language: python

python:
  - 2.7
  - 3.5

matrix:
  allow_failures:
    - python: 3.5

before_script:
  - pip install -e .[test]
  - pip install -Iv "codeclimate-test-reporter<4.4"

script:
  - python setup.py test
#  - py.test --cov=deploybot test/

after_success:
  - codeclimate-test-reporter
